const dataFromDB = [
    {
        id: 1,
        title: "Estación De Servicio 4 Rampas",
        image: "https://http2.mlstatic.com/D_NQ_NP_899910-MLA47862419808_102021-V.webp",
        description:"Resistente y fácil de armar!",
        detailed_description:"Divertite poniendote en marcha!! Increíble estacionamiento de tres pisos: primer piso y dos mas hacia arriba, con elevador , cargador de nafta y mini lavadero!! Pista doble giro, una vez que tiras el auto cae solo hasta el final!! Incluye, pista, pisos, elevador, mini lavadero, cuatro autos y muchos accesorios!! Disfruta de esta hermosa pista 3...2...1....go!!!",
        stock:39,
        price:5000,
        categoryId:1,
    },
    {
        id: 2,
        title: "Cocinita De Juguete",
        image: "https://http2.mlstatic.com/D_NQ_NP_633148-MLA49094511421_022022-V.webp",
        description:"Cocinita infantil con apertura de puertas",
        detailed_description:"Con esta linda cocina las nenas podrán preparar riquísimos y variados platos, desde pollo horneado, huevos fritos hasta galletitas. Incluye un montón de accesorios (utensilios de cocina, cajas de condimentos y muchos más).",
        stock:54,
        price:6500,
        categoryId:2,
    },
    {
        id: 3,
        title: "Peluche Bart",
        image: "https://static.wixstatic.com/media/807610_0bdeb0a2263140f883c6d59a442d4b51~mv2.jpg/v1/fill/w_498,h_498,al_c,q_85,usm_0.66_1.00_0.01/807610_0bdeb0a2263140f883c6d59a442d4b51~mv2.jpg",
        description:"Peluche de Bart Simpsons de Los Simpsons",
        detailed_description:"Bartholomew «Bart» J. Simpson (Bartolomeo «Bart» J. Simpson en Hispanoamérica) es uno de los personajes ficticios protagonistas de la serie de televisión de dibujos animados Los Simpson. Bart tiene diez años y es el primogénito y único hijo varón de Homer y Marge Simpson. Es el hermano mayor de Lisa y Maggie.",
        stock:35,
        price:2000,
        categoryId:1,
    },
    {
        id: 4,
        title: "Peluche Maggie",
        image: "https://lafrikileria.com/25475-large_default/peluche-maggie-los-simpson-28-cm.jpg",
        description:"Peluche de Maggie Simpson de Los Simpsons",
        detailed_description:"Margaret Simpson, conocida como Maggie Simpson, es un personaje ficticio de la serie de televisión de dibujos animados Los Simpson. Es la tercera hija del matrimonio protagonista, Homer y Marge Simpson, y la más joven de ellos. Sus hermanos mayores son Bart y Lisa Simpson. Siempre se la ve succionando un chupete y cuando camina, suele tropezar con el mono y cae de frente.",
        stock:83,
        price:2200,
        categoryId:3,
    },
    {
        id: 5,
        title: "Chupete",
        image: "https://www.suavinex.com/medias/evo-rojo-1200x1200.jpgOriginalImage-515Wx515H?context=bWFzdGVyfGltYWdlc3w5MDQ4NHxpbWFnZS9qcGVnfGltYWdlcy9oNTMvaGU3Lzg3OTk1ODY1NDk3OTAuanBnfGM0MzcyZWFlN2QzZjQyNjU4NzhiYWY4YTBiOWExYzk2NTc0M2Y2MTQ0M2EyMDJmZmNlMWQyYmZkYjk2NWMwNTY",
        description:"Chupete de color rojo",
        detailed_description:"Nueve de cada diez bebés aceptan nuestros chupetes | Diseño anatómico para un desarrollo natural de los dientes | Mango de seguridad para una fácil extracción | La tapa a presión ayuda a mantener limpio el chupete de su bebé | Fácil de esterilizar para entregar más higiene | Incluye 2 unidades | ",
        stock:79,
        price:400,
        categoryId:3,
    },
]
export default dataFromDB